# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_networks', '0007_auto_20170121_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('twitter', 'Twitter'), ('vimeo', 'Vimeo'), ('yelp', 'Yelp'), ('youtube', 'YouTube')], max_length=16, unique=True, verbose_name='provider')),
                ('url', models.URLField(verbose_name='URL')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='socialconfig',
            name='google_apikey',
            field=models.CharField(blank=True, default='AIzaSyDAx6URKWh7OAwJqKoiIkBq47mpZ0BGgR0', max_length=48, verbose_name='API Key'),
        ),
    ]
