# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-15 09:30
from __future__ import unicode_literals

import ckeditor.models
from django.db import migrations
import libs.stdimage.fields
import libs.storages.media_storage


class Migration(migrations.Migration):

    dependencies = [
        ('ckeditor', '0003_auto_20170905_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagephoto',
            name='photo',
            field=libs.stdimage.fields.StdImageField(aspects='normal', blank=True, min_dimensions=(780, 440), storage=libs.storages.media_storage.MediaStorage('page_photos'), upload_to=ckeditor.models.split_by_dirs, variations={'mobile': {'size': (480, 270)}, 'normal': {'size': (780, 440)}, 'wide': {'quality': 88, 'size': (1024, 576)}}, verbose_name='image'),
        ),
    ]
