# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-13 08:40
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import libs.autoslug
import libs.stdimage.fields
import libs.storages.media_storage
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='for seo, preview and breadcrumbs', max_length=128, verbose_name='Title')),
                ('header', models.TextField(max_length=255, verbose_name='Header')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('button_text', models.TextField(blank=True, max_length=64, verbose_name='Button text')),
                ('text_top', ckeditor.fields.CKEditorUploadField(blank=True, help_text='Image sizes: from <b>800x450</b> to <b>1024x576</b>', verbose_name='Content top')),
                ('text_bottom', ckeditor.fields.CKEditorUploadField(blank=True, help_text='Image sizes: from <b>800x450</b> to <b>1024x576</b>', verbose_name='Content bottom')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='change date')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('slug', libs.autoslug.AutoSlugField(populate_from='title', unique=True, verbose_name='slug')),
                ('sub_menu_title', models.CharField(blank=True, help_text='Only for parent services', max_length=128, verbose_name='Title')),
                ('preview_img', libs.stdimage.fields.StdImageField(aspects=('normal',), blank=True, min_dimensions=(900, 500), storage=libs.storages.media_storage.MediaStorage('services/preview'), upload_to='', variations={'admin': {'crop': False, 'size': (150, 300)}, 'mobile': {'size': (540, 300)}, 'normal': {'size': (380, 465)}}, verbose_name='preview image')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='services.Service', verbose_name='parent service')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('sort_order',),
            },
        ),
    ]
