# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-14 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_important_in_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='important_in_menu',
            field=models.BooleanField(default=False, verbose_name='important in menu'),
        ),
    ]
