# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-15 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_important_in_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_additional',
            field=models.TextField(blank=True, verbose_name='Description additional'),
        ),
    ]
