# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-15 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_description_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description_additional',
            field=models.TextField(blank=True, verbose_name='description additional'),
        ),
    ]
