# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20191227_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsconfig',
            name='popup_button_text',
            field=models.TextField(blank=True, max_length=64, verbose_name='Button text'),
        ),
        migrations.AddField(
            model_name='contactsconfig',
            name='popup_description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='contactsconfig',
            name='popup_header',
            field=models.CharField(default='', max_length=128, verbose_name='header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactsconfig',
            name='popup_visible',
            field=models.BooleanField(default=False, verbose_name='visible'),
        ),
    ]
