# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-17 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20200417_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsconfig',
            name='popup_button_link',
            field=models.TextField(blank=True, verbose_name='custom button link'),
        ),
    ]
