# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import testimonials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachable_blocks', '0005_auto_20190321_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='person name')),
                ('star', testimonials.models.IntegerRangeField()),
                ('testimonial', models.TextField(verbose_name='testimonial')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
                ('sort_order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='TestimonialsBlock',
            fields=[
                ('attachableblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attachable_blocks.AttachableBlock')),
                ('header', models.CharField(blank=True, max_length=128, verbose_name='header')),
            ],
            options={
                'verbose_name': 'Testimonial block',
                'verbose_name_plural': 'Testimonial blocks',
            },
            bases=('attachable_blocks.attachableblock',),
        ),
    ]
