# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_auto_20191111_0201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonialsblock',
            options={'verbose_name': 'Testimonials', 'verbose_name_plural': 'Testimonials'},
        ),
    ]
