# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-14 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_auto_20191111_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='position',
            field=models.CharField(default='', max_length=128, verbose_name='person position'),
            preserve_default=False,
        ),
    ]
