# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachable_blocks', '0004_auto_20170930_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachablereference',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='attachablereference',
            name='object_id',
            field=models.IntegerField(),
        ),
    ]
