# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 11:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatingVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='ip')),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='vote')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date')),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
                'ordering': ('-date',),
            },
        ),
    ]
