# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 05:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20190330_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingvote',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='ratingvote',
            name='rating',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating'),
        ),
    ]
