# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-12 11:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import libs.stdimage.fields
import libs.storages.media_storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpageconfig',
            options={},
        ),
        migrations.AddField(
            model_name='mainpageconfig',
            name='background',
            field=libs.stdimage.fields.StdImageField(aspects='normal', blank=True, min_dimensions=(1400, 800), storage=libs.storages.media_storage.MediaStorage('main/background'), upload_to='', variations={'admin': {'crop': True, 'size': (300, 150)}, 'mobile': {'crop': True, 'size': (280, 207)}, 'normal': {'crop': True, 'size': (1400, 800)}, 'tablet': {'crop': True, 'size': (260, 193)}}, verbose_name='Background'),
        ),
        migrations.AddField(
            model_name='mainpageconfig',
            name='button_text',
            field=models.TextField(blank=True, max_length=64, verbose_name='Button text'),
        ),
        migrations.AddField(
            model_name='mainpageconfig',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='mainpageconfig',
            name='header',
            field=models.TextField(default='', max_length=255, verbose_name='Header'),
        ),
        migrations.AddField(
            model_name='mainpageconfig',
            name='text',
            field=ckeditor.fields.CKEditorUploadField(blank=True, help_text='Image sizes: from <b>800x450</b> to <b>1024x576</b>', verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='mainpageconfig',
            name='title',
            field=models.CharField(blank=True, help_text='for seo, preview and breadcrumbs', max_length=128, verbose_name='Title'),
        ),
    ]
