# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-12 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191112_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageconfig',
            name='header',
            field=models.TextField(max_length=255, verbose_name='Header'),
        ),
    ]
