# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-15 09:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191112_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageconfig',
            name='text',
            field=ckeditor.fields.CKEditorUploadField(blank=True, help_text='Image sizes: from <b>780x440</b> to <b>1024x578</b>', verbose_name='Content'),
        ),
    ]
