# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-26 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191115_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpageconfig',
            name='header',
        ),
    ]
