# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachable_blocks', '0005_auto_20190321_1020'),
        ('blocks', '0002_ourteamblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentBlock',
            fields=[
                ('attachableblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attachable_blocks.AttachableBlock')),
                ('header', models.CharField(blank=True, max_length=128, verbose_name='header')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('button_text', models.TextField(blank=True, max_length=64, verbose_name='Button text')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointment',
            },
            bases=('attachable_blocks.attachableblock',),
        ),
    ]
