# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachable_blocks', '0005_auto_20190321_1020'),
        ('blocks', '0003_appointmentblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareBlock',
            fields=[
                ('attachableblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attachable_blocks.AttachableBlock')),
                ('like_slogan', models.CharField(blank=True, max_length=128, verbose_name='like slogan')),
            ],
            options={
                'verbose_name': 'Share',
                'verbose_name_plural': 'Share',
            },
            bases=('attachable_blocks.attachableblock',),
        ),
    ]
