# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_shareblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentblock',
            old_name='button_text',
            new_name='btn_text',
        ),
        migrations.AddField(
            model_name='appointmentblock',
            name='btn_link',
            field=models.TextField(blank=True, default='/contact/', help_text='Leave it blank to set contact form link', verbose_name='custom button link'),
        ),
    ]
