# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_auto_20191111_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentblock',
            name='btn_link',
            field=models.TextField(blank=True, default='/contact/', verbose_name='custom button link'),
        ),
    ]
