# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import libs.sprite_image.fields
import libs.stdimage.fields
import libs.storages.media_storage


class Migration(migrations.Migration):

    dependencies = [
        ('attachable_blocks', '0005_auto_20190321_1020'),
        ('blocks', '0006_auto_20191111_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', libs.sprite_image.fields.SpriteImageField(background='#FFFFFF', choices=[('holistic', (0, -87)), ('specialization', (-34, -87)), ('insurance', (-68, -87))], default='holistic', size=(34, 34), sprite='img/sprite.svg', verbose_name='icon')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'Advantage',
                'verbose_name_plural': 'Advantages',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsBlock',
            fields=[
                ('attachableblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attachable_blocks.AttachableBlock')),
                ('header', models.CharField(blank=True, max_length=128, verbose_name='header')),
            ],
            options={
                'verbose_name': 'Why choose us',
                'verbose_name_plural': 'Why choose us',
            },
            bases=('attachable_blocks.attachableblock',),
        ),
        migrations.AddField(
            model_name='appointmentblock',
            name='img',
            field=libs.stdimage.fields.StdImageField(aspects='normal', blank=True, min_dimensions=(250, 175), storage=libs.storages.media_storage.MediaStorage('blocks/appointments/img'), upload_to='', variations={'admin': {'crop': False, 'size': (300, 150)}, 'mobile': {'size': (125, 100)}, 'normal': {'size': (250, 175)}}, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='config',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='blocks.WhyChooseUsBlock'),
        ),
    ]
