# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery.fields
import gallery.models
import libs.storages.media_storage


class Migration(migrations.Migration):

    dependencies = [
        ('attachable_blocks', '0005_auto_20190321_1020'),
        ('gallery', '0003_auto_20190321_1020'),
        ('blocks', '0007_auto_20191111_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurMissionBlock',
            fields=[
                ('attachableblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attachable_blocks.AttachableBlock')),
                ('header', models.CharField(blank=True, max_length=128, verbose_name='header')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Our Mission',
                'verbose_name_plural': 'Our Mission',
            },
            bases=('attachable_blocks.attachableblock',),
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SliderImageItem',
            fields=[
                ('galleryitembase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gallery.GalleryItemBase')),
                ('image', gallery.fields.GalleryImageField(storage=libs.storages.media_storage.MediaStorage(), upload_to=gallery.models.generate_filepath, verbose_name='image')),
                ('image_crop', models.CharField(blank=True, editable=False, max_length=32, verbose_name='stored_crop')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='alt')),
            ],
            options={
                'verbose_name': 'image item',
                'verbose_name_plural': 'image items',
                'ordering': ('object_id', 'sort_order', 'created'),
                'abstract': False,
                'default_permissions': (),
            },
            bases=('gallery.galleryitembase',),
        ),
        migrations.AddField(
            model_name='ourmissionblock',
            name='slider',
            field=gallery.fields.GalleryField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blocks.Slider', verbose_name='slider'),
        ),
    ]
