# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-12 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import libs.sprite_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('attachable_blocks', '0005_auto_20190321_1020'),
        ('blocks', '0009_remove_appointmentblock_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Focuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', libs.sprite_image.fields.SpriteImageField(background='#FFFFFF', choices=[('AUTO ACCIDENT INJURY', (0, -87)), ('WORK COMP INJURY', (-34, -87)), ('SPORTS INJURY', (-68, -87)), ('SLIP AND FALLS INJURY', (-68, -87)), ('PERSONAL INJURY', (-68, -87))], default='AUTO ACCIDENT INJURY', size=(34, 34), sprite='img/sprite.svg', verbose_name='icon')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='title')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'Focus On',
                'verbose_name_plural': 'Focus On',
            },
        ),
        migrations.CreateModel(
            name='FocusOnBlock',
            fields=[
                ('attachableblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attachable_blocks.AttachableBlock')),
                ('header', models.CharField(blank=True, max_length=128, verbose_name='header')),
            ],
            options={
                'verbose_name': 'Focus On',
                'verbose_name_plural': 'Focus On',
            },
            bases=('attachable_blocks.attachableblock',),
        ),
        migrations.AddField(
            model_name='focuses',
            name='config',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='blocks.FocusOnBlock'),
        ),
    ]
