# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-12 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0010_auto_20191111_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focuses',
            name='config',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='focuses', to='blocks.FocusOnBlock'),
        ),
    ]
