# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-12 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import libs.file_field.fields
import libs.stdimage.fields
import libs.storages.media_storage


class Migration(migrations.Migration):

    dependencies = [
        ('attachable_blocks', '0005_auto_20190321_1020'),
        ('blocks', '0012_insurancesblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', libs.file_field.fields.ImageField(blank=True, storage=libs.storages.media_storage.MediaStorage('blocks/partners/img'), upload_to='', verbose_name='image')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='PartnersBlock',
            fields=[
                ('attachableblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attachable_blocks.AttachableBlock')),
                ('header', models.CharField(blank=True, max_length=128, verbose_name='header')),
            ],
            options={
                'verbose_name': 'Partners',
                'verbose_name_plural': 'Partners',
            },
            bases=('attachable_blocks.attachableblock',),
        ),
        migrations.AlterModelOptions(
            name='insurancesblock',
            options={'verbose_name': 'Insurances', 'verbose_name_plural': 'Insurances'},
        ),
        migrations.AlterField(
            model_name='insurancesblock',
            name='img',
            field=libs.stdimage.fields.StdImageField(aspects='normal', blank=True, min_dimensions=(650, 545), storage=libs.storages.media_storage.MediaStorage('blocks/insurances/img'), upload_to='', variations={'admin': {'crop': False, 'size': (300, 150)}, 'mobile': {'size': (325, 275)}, 'normal': {'size': (650, 550)}}, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='partners',
            name='config',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='blocks.PartnersBlock'),
        ),
    ]
