# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-12 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0013_auto_20191112_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whychooseusblock',
            options={'verbose_name': 'Why Choose Us', 'verbose_name_plural': 'Why Choose Us'},
        ),
    ]
