# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-12 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachable_blocks', '0005_auto_20190321_1020'),
        ('blocks', '0014_auto_20191112_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBlock',
            fields=[
                ('attachableblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attachable_blocks.AttachableBlock')),
                ('header', models.CharField(blank=True, max_length=128, verbose_name='header')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
            },
            bases=('attachable_blocks.attachableblock',),
        ),
    ]
