# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-13 06:13
from __future__ import unicode_literals

from django.db import migrations
import libs.sprite_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0015_blogblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantages',
            options={'ordering': ('sort_order',), 'verbose_name': 'Advantage', 'verbose_name_plural': 'Advantages'},
        ),
        migrations.AlterModelOptions(
            name='focuses',
            options={'ordering': ('sort_order',), 'verbose_name': 'Focus On', 'verbose_name_plural': 'Focus On'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'ordering': ('sort_order',), 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterField(
            model_name='focuses',
            name='icon',
            field=libs.sprite_image.fields.SpriteImageField(background='#FFFFFF', choices=[('auto-accident', (0, -87)), ('work-comp', (-34, -87)), ('sports', (-68, -87)), ('slip-and-falls', (-68, -87)), ('personal', (-68, -87))], default='auto-accident', size=(34, 34), sprite='img/sprite.svg', verbose_name='icon'),
        ),
    ]
