# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-13 09:23
from __future__ import unicode_literals

from django.db import migrations
import libs.stdimage.fields
import libs.storages.media_storage


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0017_serviceblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationblock',
            name='img',
            field=libs.stdimage.fields.StdImageField(aspects='normal', blank=True, min_dimensions=(580, 324), storage=libs.storages.media_storage.MediaStorage('blocks/location/img'), upload_to='', variations={'admin': {'crop': False, 'size': (300, 150)}, 'mobile': {'size': (295, 200)}, 'normal': {'size': (580, 324)}}, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='ourteamblock',
            name='img',
            field=libs.stdimage.fields.StdImageField(aspects='normal', blank=True, min_dimensions=(580, 324), storage=libs.storages.media_storage.MediaStorage('blocks/our_team/img'), upload_to='', variations={'admin': {'crop': False, 'size': (300, 150)}, 'mobile': {'size': (295, 200)}, 'normal': {'size': (580, 324)}}, verbose_name='image'),
        ),
    ]
