# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-14 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0019_contactblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactblock',
            name='consultation_btn_text',
            field=models.CharField(blank=True, max_length=64, verbose_name='consultation btn text'),
        ),
        migrations.AddField(
            model_name='contactblock',
            name='consultation_title',
            field=models.CharField(blank=True, max_length=16, verbose_name='consultation title'),
        ),
    ]
