# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-14 09:47
from __future__ import unicode_literals

from django.db import migrations
import libs.stdimage.fields
import libs.storages.media_storage


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0020_auto_20191113_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancesblock',
            name='img',
            field=libs.stdimage.fields.StdImageField(aspects='normal', blank=True, min_dimensions=(646, 545), storage=libs.storages.media_storage.MediaStorage('blocks/insurances/img'), upload_to='', variations={'admin': {'crop': False, 'size': (300, 150)}, 'mobile': {'size': (325, 275)}, 'normal': {'size': (646, 550)}}, verbose_name='image'),
        ),
    ]
