# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-15 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0021_auto_20191114_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceblock',
            options={'default_permissions': (), 'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
    ]
