# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-15 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0022_auto_20191114_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='link',
            field=models.URLField(blank=True, verbose_name='partner link'),
        ),
    ]
