# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-04 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0023_partners_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentblock',
            name='btn_link',
            field=models.TextField(blank=True, verbose_name='custom button link'),
        ),
    ]
