# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0008_auto_20181121_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoconfig',
            name='company_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='company name for meta title default'),
        ),
    ]
