# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 07:27
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import libs.stdimage.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='for seo, preview and breadcrumbs', max_length=128, verbose_name='Title')),
                ('header', models.TextField(max_length=255, verbose_name='Header')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('button_text', models.TextField(blank=True, max_length=64, verbose_name='Button text')),
                ('text_top', ckeditor.fields.CKEditorUploadField(blank=True, help_text='Image sizes: from <b>800x450</b> to <b>1024x576</b>', verbose_name='Content top')),
                ('text_bottom', ckeditor.fields.CKEditorUploadField(blank=True, help_text='Image sizes: from <b>800x450</b> to <b>1024x576</b>', verbose_name='Content bottom')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='change date')),
                ('background', libs.stdimage.fields.StdImageField(aspects='normal', blank=True, min_dimensions=(1920, 660), upload_to='base_page', variations={'admin': {'crop': True, 'size': (300, 150)}, 'desktop': {'size': (1470, 510)}, 'mobile': {'size': (640, 380)}, 'tablet': {'size': (767, 400)}, 'wide': {'size': (1920, 660)}}, verbose_name='Background')),
            ],
            options={
                'verbose_name': 'settings',
                'abstract': False,
                'default_permissions': ('change',),
            },
        ),
    ]
