# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 08:17
from __future__ import unicode_literals

from django.db import migrations
import libs.stdimage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpageconfig',
            name='background',
            field=libs.stdimage.fields.StdImageField(aspects='normal', blank=True, min_dimensions=(1920, 660), upload_to='base_page', variations={'admin': {'crop': True, 'size': (300, 150)}, 'mobile': {'size': (640, 380)}, 'normal': {'size': (1470, 510)}, 'tablet': {'size': (767, 400)}, 'wide': {'size': (1920, 660)}}, verbose_name='Background'),
        ),
    ]
