# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_locationpageconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationpageconfig',
            options={'verbose_name': 'location'},
        ),
    ]
