# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-12 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20191111_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpageconfig',
            name='background',
        ),
        migrations.RemoveField(
            model_name='locationpageconfig',
            name='background',
        ),
    ]
