# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-26 10:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20191115_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPageConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='for seo, preview and breadcrumbs', max_length=128, verbose_name='Title')),
                ('header', models.TextField(max_length=255, verbose_name='Header')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('button_text', models.TextField(blank=True, max_length=64, verbose_name='Button text')),
                ('text_top', ckeditor.fields.CKEditorUploadField(blank=True, help_text='Image sizes: from <b>780x440</b> to <b>1024x578</b>', verbose_name='Content top')),
                ('text_bottom', ckeditor.fields.CKEditorUploadField(blank=True, help_text='Image sizes: from <b>780x440</b> to <b>1024x578</b>', verbose_name='Content bottom')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='change date')),
            ],
            options={
                'verbose_name': 'our team',
            },
        ),
    ]
