# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-27 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_teampageconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpageconfig',
            name='title',
            field=models.CharField(help_text='for seo, preview and breadcrumbs', max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='locationpageconfig',
            name='title',
            field=models.CharField(help_text='for seo, preview and breadcrumbs', max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='teampageconfig',
            name='title',
            field=models.CharField(help_text='for seo, preview and breadcrumbs', max_length=128, verbose_name='Title'),
        ),
    ]
